
os: osx

before_install:
    # first uninstall a conflicting package
    - brew cask uninstall oclint

    # update and install required packages
    - brew update
    - brew install gcc
    # - brew install cmake # cmake is already installed in the default mac image

before_script:
    - mkdir build
    - cd build
    - cmake ..
  
script:
    - make 
    # Run your build commands next